import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext(null);

const TRANSLATIONS = {
  en: {
    navHomes: "Homes",
    navCrafts: "Crafts",
    navCafes: "Cafes",
    becomeHost: "Become a host",
    logIn: "Log in",
    myActivity: "My Activity",
    signOut: "Sign out",
    heroEyebrow: "Uzbekistan, the local way",
    heroTitle1: "Stay, eat & shop with",
    heroTitle2: "real Uzbek families.",
    heroSubtitle: "Homestays, handmade crafts, and family cafes — booked directly, no tourist markup.",
    searchPlaceholder: "Try 'Samarkand' or 'Bukhara'...",
    statHomestays: "homestays",
    statCrafts: "craft makers",
    statCafes: "local cafes",
    journeyEyebrow: "The Budgetravel Journey",
    journeyTitle: "From landing to lifelong memories.",
    howItWorksEyebrow: "How It Works",
    howItWorksTitle: "Four steps to the real Uzbekistan.",
    step1Title: "Browse",
    step1Body: "Explore real homestays, crafts, and cafes across Uzbekistan.",
    step2Title: "Book directly",
    step2Body: "Send a request — no middleman, no markup, straight to the host.",
    step3Title: "Meet your host",
    step3Body: "Connect on Telegram, confirm details, and arrive as a guest, not a tourist.",
    step4Title: "Take home the story",
    step4Body: "Leave with real memories — and something handmade to remember them by.",
    faqEyebrow: "FAQ",
    faqTitle: "Good to know.",
    seeAll: "See all",
    faq1Q: "Do I pay through the app?",
    faq1A: "Not yet — requests are sent through budgetravel, but payment is arranged directly with your host once you connect.",
    faq2Q: "How do I contact my host?",
    faq2A: "Every listing includes a direct Telegram button once you send a request, so you can confirm details and coordinate directly.",
    faq3Q: "How do I become a host?",
    faq3A: "Tap \"Become a host\" and apply — we personally review every application and reach out within a few days.",
    faq4Q: "Is my booking guaranteed the moment I request it?",
    faq4A: "Not automatically — a request goes to the host, and you'll hear back from them directly to confirm.",
    homesTitle: "Homestays",
    homesSubtitle: "Real Uzbek homes — breakfast, tea, and a family, not a front desk.",
    craftsTitle: "Handmade Crafts",
    craftsSubtitle: "Bought straight from the artisan who made it — no middleman.",
    cafesTitle: "Local Cafes",
    cafesSubtitle: "Where Uzbek families actually eat — not the tourist-priced spots.",
    searchByNameCity: "Search by name or city...",
    filterAll: "All",
    showingHomes: "Showing {filtered} of {total} homestays",
    showingCrafts: "Showing {filtered} of {total} crafts",
    showingCafes: "Showing {filtered} of {total} cafes",
    noHomesMatch: "No homestays match your search. Try a different city or clear your search.",
    noCraftsMatch: "No crafts match your search. Try a different city or clear your search.",
    noCafesMatch: "No cafes match your search. Try a different city or clear your search.",
    journeyStop1: "Land in Uzbekistan",
    journeyStop1Detail: "Touch down and start exploring",
    journeyStop2: "Stay with a family",
    journeyStop2Detail: "Real homes, real hospitality",
    journeyStop3: "Taste real food",
    journeyStop3Detail: "Home cooked, not tourist priced",
    journeyStop4: "Bring home a craft",
    journeyStop4Detail: "Straight from the artisan",
    journeyStop5: "Share the story",
    journeyStop5Detail: "Memories that stay with you",
    footerTagline: "Homestays, handmade crafts, and family cafes across Uzbekistan — booked directly, no tourist markup.",
    footerExplore: "Explore",
    footerCommunity: "Community",
    footerRights: "All rights reserved.",
    footerMadeWith: "Made with care for real Uzbekistan travel.",
  },
  ru: {
    navHomes: "Дома",
    navCrafts: "Ремёсла",
    navCafes: "Кафе",
    becomeHost: "Стать хозяином",
    logIn: "Войти",
    myActivity: "Моя активность",
    signOut: "Выйти",
    heroEyebrow: "Узбекистан по-настоящему",
    heroTitle1: "Живите, ешьте и покупайте у",
    heroTitle2: "настоящих узбекских семей.",
    heroSubtitle: "Домашние гостиницы, ремёсла и семейные кафе — напрямую, без туристической наценки.",
    searchPlaceholder: "Например, «Самарканд» или «Бухара»...",
    statHomestays: "домов",
    statCrafts: "мастеров",
    statCafes: "кафе",
    journeyEyebrow: "Путешествие с Budgetravel",
    journeyTitle: "От прибытия до незабываемых воспоминаний.",
    howItWorksEyebrow: "Как это работает",
    howItWorksTitle: "Четыре шага к настоящему Узбекистану.",
    step1Title: "Смотрите",
    step1Body: "Изучите настоящие дома, ремёсла и кафе по всему Узбекистану.",
    step2Title: "Бронируйте напрямую",
    step2Body: "Отправьте запрос — без посредников и наценок, напрямую хозяину.",
    step3Title: "Познакомьтесь с хозяином",
    step3Body: "Свяжитесь в Telegram, уточните детали и приезжайте как гость, а не турист.",
    step4Title: "Увезите с собой историю",
    step4Body: "Уезжайте с настоящими воспоминаниями — и сувениром ручной работы.",
    faqEyebrow: "Вопросы",
    faqTitle: "Полезно знать.",
    seeAll: "Смотреть все",
    faq1Q: "Оплачиваю ли я через приложение?",
    faq1A: "Пока нет — запросы отправляются через budgetravel, но оплата согласовывается напрямую с хозяином после связи.",
    faq2Q: "Как связаться с хозяином?",
    faq2A: "На каждой странице есть кнопка Telegram после отправки запроса — вы сможете уточнить детали напрямую.",
    faq3Q: "Как стать хозяином?",
    faq3A: "Нажмите «Стать хозяином» и подайте заявку — мы лично рассматриваем каждую заявку и свяжемся с вами в течение нескольких дней.",
    faq4Q: "Гарантировано ли бронирование сразу после запроса?",
    faq4A: "Не автоматически — запрос уходит хозяину, и он свяжется с вами напрямую для подтверждения.",
    homesTitle: "Дома",
    homesSubtitle: "Настоящие узбекские дома — завтрак, чай и семья, а не стойка регистрации.",
    craftsTitle: "Ремёсла ручной работы",
    craftsSubtitle: "Куплено напрямую у мастера — без посредников.",
    cafesTitle: "Местные кафе",
    cafesSubtitle: "Где едят настоящие узбекские семьи — а не туристические места.",
    searchByNameCity: "Поиск по названию или городу...",
    filterAll: "Все",
    showingHomes: "Показано {filtered} из {total} домов",
    showingCrafts: "Показано {filtered} из {total} изделий",
    showingCafes: "Показано {filtered} из {total} кафе",
    noHomesMatch: "Нет подходящих домов. Попробуйте другой город или очистите поиск.",
    noCraftsMatch: "Нет подходящих изделий. Попробуйте другой город или очистите поиск.",
    noCafesMatch: "Нет подходящих кафе. Попробуйте другой город или очистите поиск.",
    journeyStop1: "Прибытие в Узбекистан",
    journeyStop1Detail: "Приземлитесь и начните исследовать",
    journeyStop2: "Проживание в семье",
    journeyStop2Detail: "Настоящие дома, настоящее гостеприимство",
    journeyStop3: "Настоящая еда",
    journeyStop3Detail: "Домашняя, а не по туристическим ценам",
    journeyStop4: "Ремесло на память",
    journeyStop4Detail: "Напрямую от мастера",
    journeyStop5: "Поделитесь историей",
    journeyStop5Detail: "Воспоминания, которые останутся с вами",
    footerTagline: "Домашние гостиницы, ремёсла и семейные кафе по всему Узбекистану — напрямую, без туристической наценки.",
    footerExplore: "Разделы",
    footerCommunity: "Сообщество",
    footerRights: "Все права защищены.",
    footerMadeWith: "Сделано с заботой о настоящих путешествиях по Узбекистану.",
  },
  uz: {
    navHomes: "Uylar",
    navCrafts: "Hunarlar",
    navCafes: "Kafelar",
    becomeHost: "Mezbon bo'ling",
    logIn: "Kirish",
    myActivity: "Mening faoliyatim",
    signOut: "Chiqish",
    heroEyebrow: "O'zbekiston, mahalliy tarzda",
    heroTitle1: "Haqiqiy o'zbek oilalari bilan",
    heroTitle2: "yashang, yeng va xarid qiling.",
    heroSubtitle: "Uy sharoitida yashash, hunarmandchilik va oilaviy kafelar — bevosita, sayyoh narxisiz.",
    searchPlaceholder: "Masalan, 'Samarqand' yoki 'Buxoro'...",
    statHomestays: "uy",
    statCrafts: "hunarmand",
    statCafes: "kafe",
    journeyEyebrow: "Budgetravel sayohati",
    journeyTitle: "Qo'nishdan umrbod xotiralargacha.",
    howItWorksEyebrow: "Bu qanday ishlaydi",
    howItWorksTitle: "Haqiqiy O'zbekistonga to'rt qadam.",
    step1Title: "Ko'rib chiqing",
    step1Body: "O'zbekiston bo'ylab haqiqiy uylar, hunarlar va kafelarni kashf eting.",
    step2Title: "Bevosita band qiling",
    step2Body: "So'rov yuboring — vositachisiz, ustama narxsiz, to'g'ridan-to'g'ri mezbonga.",
    step3Title: "Mezboningiz bilan tanishing",
    step3Body: "Telegram orqali bog'laning, tafsilotlarni tasdiqlang va sayyoh emas, mehmon sifatida keling.",
    step4Title: "Hikoyani uyga olib boring",
    step4Body: "Haqiqiy xotiralar — va qo'lda yasalgan sovg'a bilan qayting.",
    faqEyebrow: "Savol-javob",
    faqTitle: "Bilishingiz kerak.",
    seeAll: "Barchasini ko'rish",
    faq1Q: "Ilova orqali to'layman-mi?",
    faq1A: "Hali yo'q — so'rovlar budgetravel orqali yuboriladi, lekin to'lov bog'langaningizdan so'ng mezbon bilan bevosita kelishiladi.",
    faq2Q: "Mezbonim bilan qanday bog'lanaman?",
    faq2A: "So'rov yuborganingizdan so'ng har bir e'londa Telegram tugmasi mavjud — tafsilotlarni bevosita kelishishingiz mumkin.",
    faq3Q: "Qanday qilib mezbon bo'laman?",
    faq3A: "\"Mezbon bo'ling\" tugmasini bosing va ariza qoldiring — biz har bir arizani shaxsan ko'rib chiqamiz va bir necha kun ichida bog'lanamiz.",
    faq4Q: "So'rov yuborilgan zahoti bron kafolatlanadi-mi?",
    faq4A: "Avtomatik emas — so'rov mezbonga boradi, va u tasdiqlash uchun siz bilan bevosita bog'lanadi.",
    homesTitle: "Uylar",
    homesSubtitle: "Haqiqiy o'zbek uylari — nonushta, choy va oila, resepshn emas.",
    craftsTitle: "Qo'lda yasalgan buyumlar",
    craftsSubtitle: "To'g'ridan-to'g'ri ustadan sotib olingan — vositachisiz.",
    cafesTitle: "Mahalliy kafelar",
    cafesSubtitle: "O'zbek oilalari haqiqatan ovqatlanadigan joylar.",
    searchByNameCity: "Nomi yoki shahar bo'yicha qidiring...",
    filterAll: "Barchasi",
    showingHomes: "{total} tadan {filtered} ta uy ko'rsatilmoqda",
    showingCrafts: "{total} tadan {filtered} ta buyum ko'rsatilmoqda",
    showingCafes: "{total} tadan {filtered} ta kafe ko'rsatilmoqda",
    noHomesMatch: "Mos uy topilmadi. Boshqa shahar tanlang yoki qidiruvni tozalang.",
    noCraftsMatch: "Mos buyum topilmadi. Boshqa shahar tanlang yoki qidiruvni tozalang.",
    noCafesMatch: "Mos kafe topilmadi. Boshqa shahar tanlang yoki qidiruvni tozalang.",
    journeyStop1: "O'zbekistonga qo'ning",
    journeyStop1Detail: "Qo'ning va his qilishni boshlang",
    journeyStop2: "Oila bilan yashang",
    journeyStop2Detail: "Haqiqiy uylar, haqiqiy mehmondo'stlik",
    journeyStop3: "Haqiqiy taomni tating",
    journeyStop3Detail: "Uy taomi, sayyoh narxida emas",
    journeyStop4: "Hunar buyumini olib qayting",
    journeyStop4Detail: "To'g'ridan-to'g'ri ustadan",
    journeyStop5: "Hikoyani ulashing",
    journeyStop5Detail: "Siz bilan qoladigan xotiralar",
    footerTagline: "O'zbekiston bo'ylab uy sharoitida yashash, hunarmandchilik va oilaviy kafelar — bevosita, sayyoh narxisiz.",
    footerExplore: "Bo'limlar",
    footerCommunity: "Jamoa",
    footerRights: "Barcha huquqlar himoyalangan.",
    footerMadeWith: "Haqiqiy O'zbekiston sayohati uchun g'amxo'rlik bilan yaratilgan.",
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("bt_lang") || "en");

  useEffect(() => {
    localStorage.setItem("bt_lang", lang);
  }, [lang]);

  const t = (key, vars) => {
    let str = TRANSLATIONS[lang][key] || TRANSLATIONS.en[key] || key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, v);
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}